[colors.cursor]
cursor = "#ffffff"

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 12

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-frappe.toml"]
