[colors.cursor]
cursor = "#8caaee"

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"

[window.padding]
x = 9
y = 6

[font]
size = 14

[font.offset]
x = 1

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "ExtraLight"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "ExtraLight Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Regular Italic"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-frappe.toml"]
