# For help with configuration see https://github.com/rszyma/kanata-tray/blob/main/README.md#configuration
"$schema" = "https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json"

[defaults]
kanata_executable = '/opt/homebrew/bin/kanata'
tcp_port = 5829

[defaults.layer_icons]

[presets.'builtin']
kanata_config = '~/.config/kanata/mac-builtin.kbd'
autorun = true

[presets.'voyager']
kanata_config = '~/.config/kanata/mac-voyager.kbd'
autorun = false

[presets.'wooting']
kanata_config = '~/.config/kanata/mac-wooting.kbd'
autorun = false
